name: petilla_app_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Localization
  easy_localization: ^3.0.1

  #State Management
  path_provider: ^2.0.11
  provider: ^6.0.4
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  mobx_codegen: ^2.1.1
  change_app_package_name: ^1.1.0

  #Routing
  go_router: ^5.2.0

  #Firebase 
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.0
  firebase_auth: ^3.5.0
  firebase_storage: ^10.3.4

  #Animation
  lottie: ^1.3.0
  quickalert: ^0.0.2
  smooth_page_indicator: ^1.0.0+2
  
  #Icons
  flutter_svg: ^1.1.3

  # Local Database
  shared_preferences: ^2.0.15

  #Admob
  google_mobile_ads: ^2.3.0
  
  #Image
  flutter_image_compress: ^1.1.0
  image_picker: ^0.8.5+3

  #Maps 
  # geolocator: ^9.0.2
  #google_maps_flutter: ^2.2.1

  # Utility
  device_preview: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.7
  intl_phone_field: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2

  flutter_lints: ^2.0.0

  #Splash Screen
  flutter_native_splash: ^2.2.16

  #App Icon
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/svg/
    - assets/jsons/lang/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
